"""added Review columns, added image url to User, added description to Gear

Revision ID: 0f5be4a35095
Revises: 7ccbb2ff85dc
Create Date: 2023-04-08 15:32:52.554715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5be4a35095'
down_revision = '7ccbb2ff85dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gears', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('gears', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
